// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shoppia.Models;

public partial class ClientAddress
{
    [Key]
    public int ClientAddressesId { get; set; }

    public int ClientId { get; set; }

    [StringLength(500)]
    public string Addresses { get; set; }

    public bool IsDefault { get; set; }

    [ForeignKey("ClientId")]
    [InverseProperty("ClientAddresses")]
    public virtual Client Client { get; set; }
}