// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shoppia.Models;

public partial class SupplyOrderDetail
{
    [Key]
    public int SupplyOrderDetailId { get; set; }

    public int SupplyOrderId { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "decimal(9, 2)")]
    public decimal UnitPrice { get; set; }

    [Column(TypeName = "decimal(9, 2)")]
    public decimal Total { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("SupplyOrderDetails")]
    public virtual Product Product { get; set; }

    [ForeignKey("SupplyOrderId")]
    [InverseProperty("SupplyOrderDetails")]
    public virtual SupplyOrder SupplyOrder { get; set; }
}