// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shoppia.Models;

public partial class SupplyOrder
{
    [Key]
    public int SupplyOrderId { get; set; }

    [Column(TypeName = "decimal(12, 2)")]
    public decimal Total { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SupplyDate { get; set; }

    public int VendorId { get; set; }

    [InverseProperty("SupplyOrder")]
    public virtual ICollection<SupplyOrderDetail> SupplyOrderDetails { get; set; } = new List<SupplyOrderDetail>();

    [ForeignKey("VendorId")]
    [InverseProperty("SupplyOrders")]
    public virtual Vendor Vendor { get; set; }
}