// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shoppia.Models;

[Index("Email", Name = "UQ__User__A9D105342C3BEA24", IsUnique = true)]
public partial class User
{
    [Key]
    public string Id { get; set; }

    [Required]
    [StringLength(256)]
    public string Email { get; set; }

    [Required]
    public string PasswordHash { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Users")]
    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}