// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shoppia.Models;

public partial class Vendor
{
    [Key]
    public int VendorId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(250)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(11)]
    [Unicode(false)]
    public string Mobile { get; set; }

    [StringLength(300)]
    public string Address { get; set; }

    public bool IsActive { get; set; }

    public bool IsBlacklist { get; set; }

    [InverseProperty("Vendor")]
    public virtual ICollection<SupplyOrder> SupplyOrders { get; set; } = new List<SupplyOrder>();
}